ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: "pavel"
  password:
    "1"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
