ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: "pavel"
  password:
    "1"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
jwt:
  secret: "pPBK7wHvJOoH+V6ORokNhZIiLF11j/7hJmRW8hxuXy0="
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"